// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PSPBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderItemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("item_discount_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("product_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<int?>("reservation_id")
                        .HasColumnType("int");

                    b.Property<int?>("tax_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("variation_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("variations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("PSPBackend.Model.BusinessModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("business_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("business_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("PSPBackend.Model.DiscountModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("business_id")
                        .HasColumnType("int");

                    b.Property<string>("code_hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discount_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("discount_percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("discount_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("valid_from")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("valid_until")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("PSPBackend.Model.OrderModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("business_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("employee_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("order_discount_percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("order_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tax_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("total_discount_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PSPBackend.Model.PaymentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("business_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("gift_card_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("order_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("order_id")
                        .HasColumnType("int");

                    b.Property<int?>("payment_method")
                        .HasColumnType("int");

                    b.Property<int?>("payment_status")
                        .HasColumnType("int");

                    b.Property<decimal?>("tip_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("PSPBackend.Model.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<bool>("CanDiscountBeApplied")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<bool>("StockQuantity")
                        .HasColumnType("bit");

                    b.Property<int>("TaxId")
                        .HasColumnType("int");

                    b.Property<string>("Variations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PSPBackend.Model.ReservationModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("appointment_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("business_id")
                        .HasColumnType("int");

                    b.Property<string>("client_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("duration")
                        .HasColumnType("int");

                    b.Property<int?>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("service_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("PSPBackend.Model.TaxModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("is_valid")
                        .HasColumnType("bit");

                    b.Property<string>("tax_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tax_rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Tax");
                });

            modelBuilder.Entity("OrderItemModel", b =>
                {
                    b.HasOne("PSPBackend.Model.OrderModel", "Order")
                        .WithMany("items")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PSPBackend.Model.OrderModel", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
